WebSite/Controllers/DashboardController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace WebSite.Controllers
{

    [Authorize(Roles = "User")]
    public class DashboardController : BaseController
    {
        public DashboardController()
        {
            
        }

        //
        // GET: /Manage/Index
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebSite/Controllers/InstitutionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;

using DataTables.AspNet.Core;
using DataTables.AspNet.Mvc5;

using AutoMapper;

using DataTables.AspNet.AspNet5.Extensions.Linq;

using BusinessLogic.Services;
using BusinessLogic.Models;

namespace WebSite.Controllers
{
    using BusinessLogic.Objects;
    using Core.Identity;
    using FineUploader;
    using System.IO;
    using ViewModels;
    using ViewModels.Institution;
    using ViewModels.Mapping;

    [Authorize(Roles = "User")]
    public class InstitutionController : BaseController
    {
        private IInstitutionService institutionService;
        private IServiceTagService serviceTagService;
        private IInstitutionTypeService institutionTypeService;
        private IKitchenService kitchenService;

        IMapper mapper;

        private int UserId
        {
            get { return int.Parse(User.Identity.GetUserId()); }
        }

        public InstitutionController(IInstitutionService institutionService, IMapper mapper, IServiceTagService serviceTagService, IInstitutionTypeService institutionTypeService, IKitchenService kitchenService)
        {
            this.institutionService = institutionService;
            this.serviceTagService = serviceTagService;
            this.institutionTypeService = institutionTypeService;
            this.kitchenService = kitchenService;

            this.mapper = mapper;
        }

        // GET: Institution
        public ActionResult Index()
        {
            var institutions = institutionService.GetByUserId(UserId);
            var model = mapper.Map<List<InstitutionShortViewModel>>(institutions);

            return View(model);
        }

        public ActionResult View(int id)
        {
            Institution institution = institutionService.GetByUserId(UserId).Where(x => x.Id == id).FirstOrDefault();

            var model = mapper.Map<InstitutionShortViewModel>(institution);

            return View(model);
        }

        public ActionResult ConfirmDeleteInstitution(int id)
        {
            Institution institution = institutionService.GetByUserId(UserId).Where(x => x.Id == id).FirstOrDefault();

            var model = mapper.Map<InstitutionShortViewModel>(institution);

            return View(model);
        }

        public ActionResult Create()
        {
            var model = new InstitutionShortViewModel();

            return View("Views/Institutions/Edit", model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var serviceTags = serviceTagService.GetAll().ToList();
            List<ComboBoxViewModel> serviceTagList = mapper.Map<List<ServiceTag>, List<ComboBoxViewModel>>(serviceTags);

            var institutionTypes = institutionTypeService.GetAll().ToList();
            List<ComboBoxViewModel> institutionTypeList = mapper.Map<List<InstitutionType>, List<ComboBoxViewModel>>(institutionTypes);

            var kitchens = kitchenService.GetAll().ToList();
            List<ComboBoxViewModel> kitchenList = mapper.Map<List<Kitchen>, List<ComboBoxViewModel>>(kitchens);

            var model = new InstitutionFullViewModel(serviceTagList, institutionTypeList, kitchenList);
            
            Institution institution = institutionService.GetByUserId(UserId).Where(x => x.Id == id).FirstOrDefault();
            mapper.Map<Institution, InstitutionFullViewModel>(institution, model);

            model.ServiceTag = institution.ServiceTags.Select(s => s.Id).ToList();

            string dir = $"{AppDomain.CurrentDomain.BaseDirectory}\\Uploads\\Institutions\\{id}";
            List<string> allowedExtensions = new List<string> { "png", "jpg", "jpeg" };
            
            var files = Directory.GetFiles(dir);
            foreach (var file in files)
            {
                string extension = file.Split('.').LastOrDefault() ?? "none";

                if (allowedExtensions.Contains(extension))
                {
                    FileInfo fileInfo = new FileInfo(file);
                    model.PhotoList.Add($"/uploads/institutions/{id}/{fileInfo.Name}");
                }
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(int id, InstitutionFullViewModel model)
        {
            if (ModelState.IsValid)
            {
                InstitutionFull info = mapper.Map<InstitutionFullViewModel, InstitutionFull>(model);

                institutionService.Save(UserId, info);
            }

            var serviceTags = serviceTagService.GetAll().ToList();
            List<ComboBoxViewModel> serviceTagList = mapper.Map<List<ServiceTag>, List<ComboBoxViewModel>>(serviceTags);

            var institutionTypes = institutionTypeService.GetAll().ToList();
            List<ComboBoxViewModel> institutionTypeList = mapper.Map<List<InstitutionType>, List<ComboBoxViewModel>>(institutionTypes);

            var kitchens = kitchenService.GetAll().ToList();
            List<ComboBoxViewModel> kitchenList = mapper.Map<List<Kitchen>, List<ComboBoxViewModel>>(kitchens);

            model.ServiceTagList = serviceTagList;
            model.InstitutionTypeList = institutionTypeList;
            model.KitchenList = kitchenList;

            return View(model);
        }

        [HttpPost]
        public FineUploaderResult UploadPhoto(FineUpload upload, int id)
        {
            FineUploaderResult answer = new FineUploaderResult(false, error: "Error"); ;

            string dir = $"{AppDomain.CurrentDomain.BaseDirectory}\\Uploads\\Institutions\\{id}";
            List<string> allowedExtensions = new List<string> { "png", "jpg", "jpeg" };
            string extension = upload.Filename.Split('.').LastOrDefault() ?? "none";

            if (allowedExtensions.Contains(extension))
            {
                string filename = System.Guid.NewGuid().ToString() + "." + extension;
                string filePath = Path.Combine(dir, filename);

                try
                {
                    upload.SaveAs(filePath);
                }
                catch (Exception ex)
                {
                    answer = new FineUploaderResult(false, error: ex.Message);
                }

                // the anonymous object in the result below will be convert to json and set back to the browser
                answer = new FineUploaderResult(true, new { pictureName = 12345 });
            } else
            {
                answer = new FineUploaderResult(false, error: "It's not image");
            }

            return answer;
        }
    }
}

WebSite/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite.Controllers
{
    public class MenuController : BaseController
    {
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Recipe()
        {
            return View();
        }

        public ActionResult Category()
        {
            return View();
        }
    }
}

WebSite/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite.Controllers
{
    public class StaffController : BaseController
    {
        // GET: Staff
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebSite/Views/Shared/_BaseLayout.cshtml
@using MvcSiteMapProvider.Web.Html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>    

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
        <link rel="manifest" href="/favicons/manifest.json">
        <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#f1592a">
        <meta name="theme-color" content="#f2f2f2">

        <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,700i" rel="stylesheet">
        @Styles.Render("~/bundles/main-styles")
        @Scripts.Render("~/bundles/main-scripts")

        @RenderSection("styles", required: false)
    </head>
    <body>
        @RenderBody()

        <script type="text/javascript">

            $(function () {
                site.onReady();
            });

        </script>

        @RenderSection("scripts", false)

        <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>

        <script id="validation-error-template" type="text/x-handlebars-template">
            <div class="alert alert-danger" role="alert">
                <strong><i class="glyphicon glyphicon-warning-sign"></i></strong> {{error}}
            </div>
        </script>

        @RenderSection("footer", required: false)
    </body>
</html>

WebSite/Views/Shared/_DashboardLayout.cshtml
@using MvcSiteMapProvider.Web.Html

@helper RequestIs(string url, string trueResult, string falseResult)
{
    if (url.Contains("/"))
    {
        List<string> urlList = url.Split(new string[] { "/" }, StringSplitOptions.None).ToList();
        bool isValid = true;
        for (int i = 0; i < urlList.Count; i++)
        {
            if (Request.Url.Segments[i + 1] != urlList[i] && Request.Url.Segments[i + 1] != urlList[i] + "/")
            {
                isValid = false;
                break;
            }
        }

        @(isValid ? trueResult : falseResult)
    }
    else if (url.Contains("*"))
    {
        string clearUrl = url.Replace("*", "");
        @(Request.Url.Segments[1] == clearUrl || Request.Url.Segments[1] == clearUrl + "/" ? trueResult : falseResult)
    }
    else
    {
        @(Request.Url.Segments[1] == url ? trueResult : falseResult)
    }
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    @Styles.Render("~/bundles/main-styles")
    @Scripts.Render("~/bundles/main-scripts")

    @RenderSection("styles", required: false)
</head>
<body>

    <div class="container-fluid">
        <ul class="nav nav-pills">
            <li role="presentation" class="@RequestIs("dashboard", "active", "")"><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
            <li role="presentation" class="@RequestIs("institution*", "active", "")"><a href="@Url.Action("Index", "Institution")">Заведения</a></li>
            <li role="presentation" class="dropdown @(RequestIs("menu/category", "true", "false").ToString() == "true" || RequestIs("menu/recipe", "true", "false").ToString() == "true" ? "active" : "")">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    Блюда/Категории <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li class="@RequestIs("menu/recipe", "active", "")"><a href="@Url.Action("Recipe", "Menu")">Блюда</a></li>
                    <li class="@RequestIs("menu/category", "active", "")"><a href="@Url.Action("Category", "Menu")">Категории</a></li>
                </ul>
            </li>
            <li role="presentation" class="@RequestIs("staff", "active", "")"><a href="@Url.Action("Index", "Staff")">Сотрудники</a></li>
        </ul>
        
        @RenderBody()
    </div>

    <script type="text/javascript">

            $(function () {
                site.onReady();
            });

    </script>

    @RenderSection("scripts", false)

    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <script id="validation-error-template" type="text/x-handlebars-template">
        <div class="alert alert-danger" role="alert">
            <strong><i class="glyphicon glyphicon-warning-sign"></i></strong> {{error}}
        </div>
    </script>

    <footer>
        <div class="container">
            <p class="text-muted">&copy; @DateTime.Now.Year Coffee Manager</p>
        </div>
    </footer>
</body>
</html>

WebSite/Views/Shared/_Layout.cshtml
@{
    Layout = "_BaseLayout.cshtml";
}

@helper RequestIs(string url, string trueResult, string falseResult)
{
if (url.Contains("/"))
{
    List<string> urlList = url.Split(new string[] { "/" }, StringSplitOptions.None).ToList();
    bool isValid = true;
    for (int i = 0; i < urlList.Count; i++)
    {
        if (Request.Url.Segments[i + 1] != urlList[i] && Request.Url.Segments[i + 1] != urlList[i] + "/")
        {
            isValid = false;
            break;
        }
    }

    @(isValid ? trueResult : falseResult)
}
else if (url.Contains("*"))
{
    string clearUrl = url.Replace("*", "");
        @(Request.Url.Segments[1] == clearUrl || Request.Url.Segments[1] == clearUrl + "/" ? trueResult : falseResult)
}
else
{
        @(Request.Url.Segments[1] == url ? trueResult : falseResult)
}
}

@section styles{
    @RenderSection("styles", required: false)
}

@section scripts{
    @RenderSection("scripts", required: false)
}

<nav class="navbar navbar-coffee" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <i class="icon-title">@Html.Partial("_SvgIcons", 1)</i>
                <span class="text-title">Coffee Manager</span>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav">
                @Html.MvcSiteMap().Menu()
            </ul>

            <ul class="nav navbar-nav navbar-right">
                @Html.Partial("_LogInPartial")
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

@if (User.Identity.IsAuthenticated && Url.RequestContext.RouteData.Values["controller"].ToString() != "Home")
{
    <div class="menu-coffee">
        <div class="container">
            <a href="@Url.Action("Index", "Dashboard")" class="@RequestIs("dashboard", "active", "")">
                <div class="img-item">@Html.Partial("_SvgIcons", 5)</div>
                <div class="text-item">Dashboard</div>
            </a>
            <a href="@Url.Action("Index", "Institution")" class="@RequestIs("institution*", "active", "")">
                <div class="img-item">@Html.Partial("_SvgIcons", 2)</div>
                <div class="text-item">Заведения</div>
            </a>
            <a href="#">
                <div class="img-item">@Html.Partial("_SvgIcons", 3)</div>
                <div class="text-item">Блюда</div>
            </a>
            <a href="@Url.Action("Index", "Staff")" class="@RequestIs("staff", "active", "")">
                <div class="img-item">@Html.Partial("_SvgIcons", 4)</div>
                <div class="text-item">Персонал</div>
            </a>
        </div>

        <div class="menu-selector"></div>
    </div>
}

<div class="container base-container">
            
    @Html.MvcSiteMap().SiteMapPath()

    @RenderBody()
            
</div>
    
@section footer{
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="company-name">
                        <i class="icon-title">@Html.Partial("_SvgIcons", 1)</i>
                        <span>Coffee Manager</span>
                    </div>
                    <div class="right-reserved">2017 &copy; Все права защищены</div>
                </div>

                <div class="col-sm-4">Social links</div>

                <div class="col-sm-4">
                    <nav>
                        <a href="#">О нас</a><br />
                        <a href="#">Контакты</a><br />
                        <a href="#">Правила и условия</a><br />
                        <a href="#">Политика конфиденциальности</a>
                    </nav>
                </div>
            </div>
        </div>
    </footer>
}